# Generated by Django 4.2.3 on 2024-01-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="itemtransactions", name="company",),
        migrations.RemoveField(model_name="itemtransactions", name="item",),
        migrations.RemoveField(model_name="itemtransactions", name="user",),
        migrations.RemoveField(
            model_name="itemtransactionshistory", name="transaction",
        ),
        migrations.RemoveField(model_name="itemtransactionshistory", name="user",),
        migrations.RemoveField(model_name="unit", name="company",),
        migrations.DeleteModel(name="Item",),
        migrations.DeleteModel(name="ItemTransactions",),
        migrations.DeleteModel(name="ItemTransactionsHistory",),
        migrations.DeleteModel(name="Unit",),
    ]
