# Generated by Django 4.2.6 on 2024-01-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0004_purchasebill_purchasebillitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='End_date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
