# Generated by Django 4.2.6 on 2024-01-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0005_alter_party_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='payment',
            field=models.CharField(blank=True, choices=[('To Pay', 'To Pay'), ('To Receive', 'To Receive')], max_length=100, null=True),
        ),
    ]
