# Generated by Django 4.2.6 on 2024-01-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0008_debitnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='grandtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
