# Generated by Django 4.2.6 on 2024-01-31 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0009_debitnote_grandtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='grandtotal',
        ),
        migrations.RemoveField(
            model_name='debitnote',
            name='items',
        ),
        migrations.CreateModel(
            name='DebitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('total', models.IntegerField(default=0, null=True)),
                ('subtotal', models.IntegerField(default=0, null=True)),
                ('taxamount', models.IntegerField(default=0, null=True)),
                ('adjustment', models.IntegerField(default=0, null=True)),
                ('grandtotal', models.IntegerField(default=0, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('debitnote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.debitnote')),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
