# Generated by Django 4.2.6 on 2024-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0010_remove_debitnote_amount_remove_debitnote_grandtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnoteitem',
            name='adjustment',
        ),
        migrations.RemoveField(
            model_name='debitnoteitem',
            name='grandtotal',
        ),
        migrations.RemoveField(
            model_name='debitnoteitem',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='debitnoteitem',
            name='taxamount',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='bill_no',
        ),
        migrations.AddField(
            model_name='debitnote',
            name='adjustment',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='grandtotal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='subtotal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='taxamount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
