# Generated by Django 4.2.6 on 2024-02-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0011_remove_debitnoteitem_adjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitnote',
            name='bill',
        ),
    ]
