# Generated by Django 4.2.6 on 2024-02-15 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0013_alter_debitnote_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitNoteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('C', 'Created'), ('E', 'Edited')], max_length=1)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.debitnote')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
