# Generated by Django 4.2.6 on 2024-03-07 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0016_remove_debitnoteitem_itm_hsn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='creditlimit',
        ),
        migrations.AddField(
            model_name='party',
            name='at_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='party',
            name='opening_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='party',
            name='End_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='payment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Transactions_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_type', models.CharField(max_length=255)),
                ('trans_number', models.CharField(max_length=255)),
                ('trans_date', models.DateTimeField()),
                ('total', models.CharField(max_length=255)),
                ('balance', models.CharField(max_length=255)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartyTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('transactiondate', models.DateField(auto_now=True)),
                ('Transactions_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billapp.transactions_party')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.company')),
                ('party', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
