# Generated by Django 4.2.6 on 2024-04-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billapp', '0017_remove_party_creditlimit_party_at_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partytransactionhistory',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
        migrations.AlterField(
            model_name='transactions_party',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billapp.party'),
        ),
    ]
